[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.49.0",
    "openai>=1.71.0",
    "streamlit>=1.44.1",
    "youtube-transcript-api>=1.0.3",
]
